### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by primordialfun** [Metabolix/HackBGRT#195]
**What happens?**
Cannot use ur app at all, trying to change my booting wallpaper when computer starts.
**How this happens?**
Explain exactly the steps you did:
1. Download HackBGRT-(version).zip and extract all files.
2. Start setup.
3. Select ... i selected I
4. ... Closed the paint and continue clicking by yes administrator thing and got error at the last 
[log.log](https://github.com/user-attachments/files/16319917/log.log)

The error:

2024-07-20 13:18:08.552 | pid 10140 | Disabled NVRAM entry for HackBGRT with BCDEdit.
2024-07-20 13:18:08.552 | pid 10140 | 
2024-07-20 13:18:08.552 | pid 10140 | Error: Check your configuration and try again.
2024-07-20 13:18:08.554 | pid 10140 | Setup+SetupException: Check your configuration and try again.
2024-07-20 13:18:08.554 | pid 10140 |    at Setup.<>c__DisplayClass52_0.<RunPrivilegedActions>b__0(Action revert)
2024-07-20 13:18:08.554 | pid 10140 |    at Setup.<>c__DisplayClass52_0.<RunPrivilegedActions>b__1(Action enable, Action revert)
2024-07-20 13:18:08.554 | pid 10140 |    at Setup.RunPrivilegedActions(IEnumerable`1 actions)
2024-07-20 13:18:08.554 | pid 10140 |    at Setup.Run(String[] args)
2024-07-20 13:18:08.554 | pid 10140 | If you need to report a bug,
2024-07-20 13:18:08.554 | pid 10140 |  - run this setup again with menu option L (show-boot-log)
2024-07-20 13:18:08.554 | pid 10140 |  - then include the setup.log file with your report.
2024-07-20 13:18:08.554 | pid 10140 | Press any key to quit.
2024-07-20 13:18:10.319 | pid 19868 | 
2024-07-20 13:18:10.319 | pid 19868 | Error: Privileged action (disable install enable-bcdedit) failed!
2024-07-20 13:18:10.323 | pid 19868 | Setup+SetupException: Privileged action (disable install enable-bcdedit) failed!
2024-07-20 13:18:10.323 | pid 19868 |    at Setup.RunPrivilegedActions(IEnumerable`1 actions)
2024-07-20 13:18:10.323 | pid 19868 |    at Setup.ShowMenu()
2024-07-20 13:18:10.323 | pid 19868 |    at Setup.Run(String[] args)

**Log file**
Run the setup again and select menu option `L` (or add parameter `show-boot-log` on command line). Attach the `setup.log` to this report.

**Comment by Metabolix** [comment]
Like the setup says a bit earlier:

> Verifying config: boot=\EFI\HackBGRT\bootmgfw-original.efi
> DetectLoader failed: A:\EFI\HackBGRT\bootmgfw-original.efi not found
> Error: Boot loader does not exist!

And finally:

> Error: Check your configuration and try again.

So you have changed the `config.txt` and set a boot loader path which does not exist. The default setting currently is `boot=MS` and you should not change that if you don't understand what you are doing. Do as the setup says: check your configuration and try again. Note that you cannot just copy a config.txt from some ancient version (like 1.5.1), because the config has changed.

**Comment by primordialfun** [comment]
So i need to update my config.txt right?

My config.txt looks like that now:

boot=\EFI\HackBGRT\bootmgfw-original.efi


image=x=auto,y=auto,path=\EFI\HackBGRT\splash.bmp


resolution=-1x-1

debug=0

**Comment by Metabolix** [comment]
Like I said, use the default config.txt (in the package). Do not make any changes you don't understand.
